//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.Tasks = new HashSet<Task>();
            this.SoftwareItems = new HashSet<SoftwareItem>();
        }
    
        public long ID { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime War_end_date { get; set; }
        public string Notes { get; set; }
        public string Status { get; set; }
        public long Department_ID { get; set; }
        public long Type_ID { get; set; }
        public Nullable<long> AssignedTo_Employee_ID { get; set; }
        public Nullable<System.DateTime> Deployed { get; set; }
        public Nullable<System.DateTime> Returned { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<SoftwareItem> SoftwareItems { get; set; }
    }
}
