//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentType
    {
        public EquipmentType()
        {
            this.Equipments = new HashSet<Equipment>();
            this.EquipmentType1 = new HashSet<EquipmentType>();
            this.EquipmentTypes = new HashSet<EquipmentType>();
        }
    
        public long ID { get; set; }
        public string Manufacturer { get; set; }
        public string ModelNumber { get; set; }
    
        public virtual ICollection<Equipment> Equipments { get; set; }
        public virtual ICollection<EquipmentType> EquipmentType1 { get; set; }
        public virtual ICollection<EquipmentType> EquipmentTypes { get; set; }
    }
}
