//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportGroup
    {
        public SupportGroup()
        {
            this.Tasks = new HashSet<Task>();
            this.Employees = new HashSet<Employee>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> Overseer_Employee_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
