//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Employees = new HashSet<Employee>();
            this.Equipments = new HashSet<Equipment>();
        }
    
        public long ID { get; set; }
        public string Status { get; set; }
        public string Summary { get; set; }
        public Nullable<System.DateTime> Due { get; set; }
        public string Priority { get; set; }
        public System.DateTime Submitted { get; set; }
        public string Notes { get; set; }
        public Nullable<long> Submitter_Employee_ID { get; set; }
        public Nullable<long> Assigned_Group_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SupportGroup SupportGroup { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Equipment> Equipments { get; set; }
    }
}
